version = 1

# ---------------------------
# Python Analyzer
# ---------------------------
[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["requirements.txt", "Pipfile", "pyproject.toml"]

  [analyzers.meta]
  runtime_version = "3.x.x"

  [analyzers.config]
  linting = true
  formatting = true
  check_dependencies = true
  check_security = true
  check_code_quality = true
  check_performance = true
  check_best_practices = true
  include_patterns = ["**/*.py"]

  [analyzers.auto_scan]
  run = "daily"
  trigger_on_push = true

# ---------------------------
# Transformers (Code Formatters)
# ---------------------------
[[transformers]]
name = "black"

[[transformers]]
name = "isort"

[[transformers]]
name = "ruff"

# ---------------------------
# Shell Script Analyzer
# ---------------------------
[[analyzers]]
name = "shell"
enabled = true
include_patterns = ["*.sh", "**/*.sh"]
exclude_patterns = ["node_modules/**"]

  [analyzers.config]
  linting = true